name: Build Flare Liquidity Service

on:
  push:
    branches:
      - build

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        run: |
          curl -fsSL https://bun.sh/install | bash
          echo "$HOME/.bun/bin" >> $GITHUB_PATH

      - name: Install dependencies
        run: bun install

      - name: Typecheck
        run: bunx tsc --noEmit

      - name: Build
        run: bun build src/index.ts --target=node --outdir=dist

      - name: Commit build output
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add dist

          git commit -m "chore(build): generated build output" || exit 0

          git push
